version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: jitendra93/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: jitendra93/user-service
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: jitendra93/feed-service
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: jitendra93/frontend
